# Generated by Django 5.2 on 2025-04-12 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PleasantHabit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255, verbose_name="Место")),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pleasant_habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приятная привычка",
                "verbose_name_plural": "Приятные привычки",
            },
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Указывается только для полезных привычек",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habit.pleasanthabit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
