# Generated by Django 5.2 on 2025-04-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0003_pleasanthabit_alter_habit_related_habit"),
    ]

    operations = [
        migrations.AddField(
            model_name="pleasanthabit",
            name="is_pleasant",
            field=models.BooleanField(default=True, verbose_name="Приятная привычка"),
        ),
    ]
