# Generated by Django 5.2 on 2025-04-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0004_pleasanthabit_is_pleasant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(default=False, editable=False, verbose_name="Приятная привычка"),
        ),
        migrations.AlterField(
            model_name="pleasanthabit",
            name="is_pleasant",
            field=models.BooleanField(default=True, editable=False, verbose_name="Приятная привычка"),
        ),
    ]
