# Generated by Django 5.2 on 2025-04-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Telegram chat ID"),
        ),
    ]
